#spring.application.name=PP_3_1_5_SpringBootREST_JS
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=password
#
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=create-drop

spring:
  application:
    name:
      PP_3_1_5_SpringBootREST_JS

  datasource:
    driver-class-name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/postgres
    username:
      postgres
    password:
      password

  jpa:
    show-sql:
      false
    hibernate:
      ddl-auto:
        create-drop